# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

rand_ten = torch.rand(7,7)
rand_ten
# Create random tensor


tensor([[0.2667, 0.1168, 0.3868, 0.7230, 0.1788, 0.6187, 0.7870],
        [0.7279, 0.5066, 0.7064, 0.8559, 0.8223, 0.3009, 0.4021],
        [0.0147, 0.7998, 0.3195, 0.1918, 0.7590, 0.3398, 0.5968],
        [0.4791, 0.7604, 0.6413, 0.7764, 0.9442, 0.9417, 0.7795],
        [0.2782, 0.4631, 0.2515, 0.1930, 0.7333, 0.8995, 0.8202],
        [0.2114, 0.2737, 0.8936, 0.7184, 0.0823, 0.2372, 0.4582],
        [0.7813, 0.6500, 0.3341, 0.8959, 0.0695, 0.6978, 0.0166]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
rand_ten2 = torch.rand(1,7)
rand_ten2

# Perform matrix multiplication

result = torch.matmul(rand_ten, rand_ten2.T)
result

tensor([[2.0460],
        [2.5841],
        [1.4739],
        [2.9332],
        [1.9283],
        [1.9642],
        [1.9660]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
first_ten = torch.rand(7,7)
second_ten = torch.rand(1,7)

# Matrix multiply tensors
ans = torch.matmul(first_ten, second_ten.T)
ans

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
first_ten = torch.rand(2,3).to(device)
second_ten = torch.rand(2,3).to(device)
first_ten, second_ten

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
seven = torch.matmul(first_ten, second_ten.T)

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
seven.max()
# Find min
seven.min()

tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
seven.argmax()

# Find arg min
seven.argmin()

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [25]:
# Set seed

RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
rand_ten = torch.rand(1,1,1,10)

# Remove single dimensions
result = torch.squeeze(rand_ten)

# Print out tensors and their shapes
rand_ten, result, result.shape, result.dim()

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]),
 1)